### ISSUE TITLE
How to Graph these Data?

### ISSUE THREAD

**Issue by raegan13** [fish497-2018/Jarvis_ReefFish#3]
In my question, I'm attempting to compare the amount of species present in Bootless Bay and the Museum Bootless collection. The data notes absence/presence of each species as 0/1. I'm having a really hard time thinking of how I can graph this data effectively. Does anyone have an idea of what I could do?

**Comment by sr320** [comment]
More directly you could filter rows based on value > 0  and count number of rows for each location

**Comment by raegan13** [comment]
Great, thanks for the help!

**Comment by raegan13** [comment]
Next question: I want to filter out rows that are only 0 for both Bootless and Museum.Bootless, but not rows that read 0 for only one location. Is there a way to use filter() for conditions like this?

**Comment by raegan13** [comment]
Thanks so much! I figured out a way to do it using "|".
