### ISSUE TITLE
Using Tidyr Functions

### ISSUE THREAD

**Issue by raegan13** [fish497-2018/Jarvis_ReefFish#9]
Hi! I'm still encountering issues with trying to use Tidyr to manipulate my data. I think we discussed using spread(), so I'm attempting to spread my condensed dataset by Genus, but I just turn up with a lot of NAs. Is there a better way to use Tidyr to manipulate my data?

**Comment by sr320** [comment]
what about this?
some of it might be superfluous but you could tweak.


```{r}
reef_fish %>%
  gather(`Museum.Bootless`, `Bootless`, key = "location", value = "catch_code") %>%
  select(Family, Genus, species,location, catch_code, length..cm.) %>%
  filter(catch_code == 1) %>%
  group_by(Family, location) %>%
  summarise(total_catch = sum(catch_code))
```

**Comment by raegan13** [comment]
Thank you so much! This worked really well. In fact, displaying my data this way, I fixed up all my code and thereby fixed the issue I was having with my graphs!
